spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://172.16.86.6:3306/sty?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: sty
    password: sty
    hikari:
      connection-timeout: 60000
  redis:
    host: 10.16.225.69
    port: 6379
    password: sty
  application:
    name: provider
  rabbitmq:
    host: 172.16.86.6
    port: 5672
    username: sty1
    password: sty
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.servi.cloud.provider.enty
server:
  port: 9004
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.inetutils.default-ip-address}:${spring.application.instance-id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"