spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://172.16.86.6:3306/sty?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: sty
    password: sty
    hikari:
      connection-timeout: 60000
  redis:
    host: 10.16.225.69
    port: 6379
    password: sty
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.servi.cloud.provider.enty